apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.name }}
data:
  key: {{ .Values.myobj.myproperty | quote }}
  {{- if .Values.addPackagedValue }}
  otherkey: {{ required "packagedValue was not specified!" .Values.packagedValue | quote }}
  {{- end }}
