apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test

on:
  push:
    branches:
      - '**'

jobs:
  test-minimal:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1
    - id: action
      name: Run Action
      uses: .
      with:
        chart: ./charts/example

    - name: Verify Action output
      uses: docker://alpine/helm:3.12.1
      run: |
        set -ux
        [ -d "$OUTDIR" ]
        echo "$OUTDIR" | grep -Eq "^$RUNNER_TEMP/chart-"
        [ -f "$OUTCHART" ]
        [ "$OUTCHART" = $OUTDIR/example-chart-0.0.0.tgz ]
        [ "$OUTVERSION" = 0.0.0 ]
        MANIFEST="$(helm template $OUTCHART)"
        echo "$MANIFEST" | grep -q "my value"
      env:
        OUTDIR: ${{ steps.action.outputs.directory }}
        OUTCHART: ${{ steps.action.outputs.chart }}
        OUTVERSION: ${{ steps.action.outputs.version }}

  test-maximal:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1
    - name: Modify chart to make packagedValue mandatory
      uses: docker://alpine:3.18
      run: |
        sed -Ei 's/^addPackagedValue:.*/addPackagedValue: true/' ./charts/example/values.yaml
    - id: action
      name: Run Action
      uses: .
      with:
        chart: ./charts/example
        destination: ./chart-output
        version: "0.0.7"
        app-version: "0.3.0"
        verify: "false"
        sign: "false"
        sign-key: "mykeyname"
        values: |
          packagedValue: fake value that would be a pinned image tag in practice
    - name: Verify Action output
      uses: docker://alpine/helm:3.12.1
      run: |
        set -ux
        [ -d "$OUTDIR" ]
        [ "$OUTDIR" = "./chart-output" ]
        [ -f "$OUTCHART" ]
        [ "$OUTCHART" = $OUTDIR/example-chart-0.0.7.tgz ]
        [ "$OUTVERSION" = 0.0.7 ]
        [ "$OUTNAME" = example-chart ]
        MANIFEST="$(helm template $OUTCHART)"
        echo "$MANIFEST" | grep -q "my value"
      env:
        OUTDIR: ${{ steps.action.outputs.directory }}
        OUTCHART: ${{ steps.action.outputs.chart }}
        OUTVERSION: ${{ steps.action.outputs.version }}
        OUTNAME: ${{ steps.action.outputs.name }}

